

CREATE TABLE Categorias (
    Id INT IDENTITY PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Ativo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Exames (
    Id INT IDENTITY PRIMARY KEY,
    Nome NVARCHAR(150) NOT NULL,
    Tipo NVARCHAR(100) NULL,
    CategoriaId INT NOT NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    DataCriacao DATETIME2 NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (CategoriaId) REFERENCES Categorias(Id)
);

CREATE TABLE Orientacoes (
    Id INT IDENTITY PRIMARY KEY,
    ExameId INT NOT NULL,
    Descricao NVARCHAR(MAX) NOT NULL,
    Jejum NVARCHAR(100) NULL,
    Material NVARCHAR(100) NULL,
    PrazoResultado NVARCHAR(100) NULL,
    FOREIGN KEY (ExameId) REFERENCES Exames(Id)
);


CREATE TABLE [dbo].[TB_USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[DS_NOMECOMPLETO] [varchar](150) NOT NULL,
	[DS_LOGIN] [varchar](50) NOT NULL,
	[DS_SENHA] [varchar](100) NOT NULL,
	[DS_EMAIL] [varchar](100) NULL,
	[TP_ATIVO] [char](1) NOT NULL,
	[DT_CRIACAO] [datetime] NOT NULL,
	[ID_ROLE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
);